[project]
name = "public-gateway-mcp"
version = "0.0.0"
description = "An MCP for ax-public-gateway"
readme = "README.md"
authors = [
    { name = "Sam Mosleh", email = "smosleh@axcient.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=3.4.6",
    "httpx[http2]>=0.28.1",
    "pydantic-settings>=2.0",
    "pyyaml>=6.0.3",
]
license = "Apache-2.0"
license-files = [
    "LICENSE",
]
keywords = [
    "mcp",
    "model context protocol",
    "llm",
    "agent",
]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Typing :: Typed",
]

[project.urls]
Homepage = "https://developer.axcient.com"
Repository = "https://github.com/Axcient/public-gateway-mcp"
Documentation = "https://developer.axcient.com"

[dependency-groups]
dev = [
    "mypy>=1.17.1",
    "types-PyYAML>=6.0.12",
]

[project.scripts]
public-gateway-mcp = "public_gateway_mcp.server:main"

[build-system]
requires = ["uv_build>=0.11.26,<0.12.0"]
build-backend = "uv_build"

[tool.mypy]
strict = true
plugins = ['pydantic.mypy']

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "PL",  # pylint
    "I",   # isort
    "C4",  # flake8-comprehensions
    "B",   # flake8-bugbear
    "Q",   # flake8-quotes
    "T20", # flake8-print
    "S",   # flake8-bandit
    "PIE", # flake8-pie
    "RET", # flake8-return
    "SIM", # flake8-simplify
    "TC",  # flake8-type-checking
    "C90", # mccabe
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "RUF", # ruff
]
ignore = [
    "E501", # line too long, handled by formatter
]

[tool.ruff.lint.flake8-type-checking]
runtime-evaluated-base-classes = ["pydantic.BaseModel"]
